### ISSUE TITLE
configure - brew install rust

### ISSUE THREAD

**Issue by SymbolixAU** [dirkschumacher/wasmrrr#8]
I think the [command](https://github.com/dirkschumacher/wasmr/blob/master/configure#L8) for MacOS is `brew install rust`. This just worked for me, where as `rustc` failed.

**Comment by dirkschumacher** [comment]
Thanks. I think the best way is to use https://rustup.rs/. Will change the text.

**Comment by SymbolixAU** [comment]
yeah that also works. However, using `rustup` means you have to log-out and log-in again, whereas `brew` just works out the box.
